[Editor]
Borderless = false
ExtTabline   = true
Clipboard = false
Transparent = 0.9
Macmeta = true
DrawBorder = true
IndentGuide = true
fontFamily = "RobotoMono Nerd Font Mono"
fontsize = 15
SmoothScroll = true


[Message]

[Tabline]
Visible = true

[Lint]
Visible = true

[MiniMap]
Disable = false
Visible = true

[ScrollBar]
Visible = true

[SideBar]
Visible = true
Width = 130

[Workspace]
PathStyle = "minimum"
RestoreSession = false
FileExplorerOpenCmd = ":tabnew"
